# Generated by Django 5.1.4 on 2024-12-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='capacity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='post',
            name='current_applicants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
